CREATE TABLE public.workout_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE public.workout_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES public.workout_sessions(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    exercise_name TEXT NOT NULL,
    sets INT NOT NULL,
    reps INT NOT NULL,
    weight NUMERIC(5, 2) NOT NULL,
    rest_time_seconds INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE public.nutrition_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    meal_type TEXT NOT NULL,
    food_name TEXT NOT NULL,
    calories INT NOT NULL,
    protein_g NUMERIC(4, 1) NOT NULL,
    carbs_g NUMERIC(4, 1) NOT NULL,
    fat_g NUMERIC(4, 1) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE public.profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    gender TEXT NOT NULL,
    experience TEXT NOT NULL,
    activity_level TEXT NOT NULL,
    age INT NOT NULL,
    weight NUMERIC(5, 2) NOT NULL,
    height NUMERIC(4, 1) NOT NULL,
    target_weight NUMERIC(5, 2) NOT NULL,
    body_fat NUMERIC(3, 1),
    selected_goals TEXT[] NOT NULL DEFAULT '{}',
    computed_calories INT NOT NULL
);

CREATE INDEX idx_workout_logs_user_date ON public.workout_logs(user_id, created_at DESC);
CREATE INDEX idx_nutrition_logs_user_date ON public.nutrition_logs(user_id, created_at DESC);
